# Generated by Django 4.1.7 on 2023-04-22 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from auth_app.models import TodoStatus


def add_data(apps, schema):
    TodoStatus(name='Выполнена').save()
    TodoStatus(name='Не выполнена').save()
    TodoStatus(name='Просрочена').save()
    TodoStatus(name='Отменена').save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TodoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('complete_at', models.DateTimeField(null=True)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.todostatus')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.todolist')),
            ],
        ),
        migrations.RunPython(add_data),
    ]
